services:

  sessions_hnh:
    container_name: redis_hnh
    image: redis:${REDDIS_VERSION}-alpine
    restart: always
    command: redis-server --requirepass ${REDDIS_PASSWORD}
    ports: 
      - "8008:6379"
    environment:
      - REDIS_PASSWORD=${REDDIS_PASSWORD}
    volumes:
      - $PWD/redis_data:/data

  db_hnh:
    container_name: db_hnh
    image: search_postgres
    restart: always
    environment:
      POSTGRES_DB: "hnh"
      POSTGRES_USER: vive_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migrations/hnh/:/docker-entrypoint-initdb.d/
      - hnh_data:/var/lib/postgresql/data
    ports:
      - "8054:5432"

  db_hnh_csat:
    container_name: db_hnh_csat
    image: postgres:${POSTGRES_VERSION}-alpine
    restart: always
    environment:
      POSTGRES_DB: "hnh_csat"
      POSTGRES_USER: vive_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migrations/hnh_csat/:/docker-entrypoint-initdb.d/
      - hnh_csat_data:/var/lib/postgresql/data
    ports:
      - "8055:5432"

volumes:
  hnh_data:
  hnh_csat_data:
