global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'hnh'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8081', 'node-exporter:9100']