services:

  db_hnh:
    container_name: db_hnh
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_DB: "hnh"
      POSTGRES_USER: vive_admin
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
    ports:
      - "8054:5432"
