services:

  db_hnh:
    container_name: db_hnh
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_DB: "hnh"
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./migrations/001_initial_migration.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8054:5432"
